# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run test
      # - run: ssh $SSH_USER@SSH_HOST touch test-circleCI
      - run: |
          ssh -o "StrictHostKeyChecking=no" root@158.69.112.145 touch test-circleci ; git clone git@github.com:loofat/grappling-heroes-back.git ; npm install

          # cd grappling-heroes-back ; npm install ; npm run start
